apiVersion: v1
kind: Secret
metadata:
  name: flowboard-secrets
type: Opaque
stringData:
  DB_HOST: your-db-host
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASS: password
  DB_NAME: flowboard
  JWT_SECRET: supersecretjwt
